parserOptions:
  sourceType: 'module'

env:
  es6: true
  browser: true

extends:
  - 'airbnb'

rules:
  comma-dangle:
    - error
    - never
  prefer-object-spread: 0
  arrow-parens: 0
  implicit-arrow-linebreak: 0
  function-paren-newline: 0
  indent:
    - error
    - 2
    - MemberExpression: 0
  prefer-promise-reject-errors: 0
  max-classes-per-file: 0
